name:                 MathDoku
version:              1.0.0.0
visibility:           public
id:                   MathDoku-1.0.0.0-JmzRP1KuBS0KuvHHyKmyT6
key:                  MathDoku-1.0.0.0-JmzRP1KuBS0KuvHHyKmyT6
license:              MIT
copyright:            2025
maintainer:           tu@equipo.com
author:               Tu equipo
homepage:             https://github.com/fabio2k3/MathDoku#readme
synopsis:             Sudoku matemático interactivo con pistas
description:
    MathDoku: Sudoku con pistas matemáticas (par/impar, primo, divisible).
    Arquitectura profesional: library + executable + tests con Stack.

category:             Game
abi:                  69569ef297bbab424c446654f77ec599
exposed:              True
exposed-modules:
    MathDoku MathDoku.Core MathDoku.GameState MathDoku.Generator
    MathDoku.Hints MathDoku.Solver MathDoku.UI MathDoku.UIHints

hidden-modules:       Paths_MathDoku
import-dirs:
    C:\Users\admin\Desktop\DeclarativaF\MathDoku\.stack-work\install\cfaefed7\lib\x86_64-windows-ghc-9.8.4\MathDoku-1.0.0.0-JmzRP1KuBS0KuvHHyKmyT6

library-dirs:
    C:\Users\admin\Desktop\DeclarativaF\MathDoku\.stack-work\install\cfaefed7\lib\x86_64-windows-ghc-9.8.4\MathDoku-1.0.0.0-JmzRP1KuBS0KuvHHyKmyT6
    C:\Users\admin\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\admin\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    C:\Users\admin\Desktop\DeclarativaF\MathDoku\.stack-work\install\cfaefed7\lib\x86_64-windows-ghc-9.8.4\MathDoku-1.0.0.0-JmzRP1KuBS0KuvHHyKmyT6
    C:\Users\admin\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\admin\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    C:\Users\admin\Desktop\DeclarativaF\MathDoku\.stack-work\install\cfaefed7\lib\x86_64-windows-ghc-9.8.4
    C:\Users\admin\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\admin\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    C:\Users\admin\Desktop\DeclarativaF\MathDoku\.stack-work\install\cfaefed7\share\x86_64-windows-ghc-9.8.4\MathDoku-1.0.0.0

hs-libraries:         HSMathDoku-1.0.0.0-JmzRP1KuBS0KuvHHyKmyT6
include-dirs:
    C:\Users\admin\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include

depends:
    MonadRandom-0.6.2-K5HBXA5MAQIEOo8cVZg2ep
    ansi-terminal-1.1.2-5tlOFCF8vCb392f6Aq8XHq base-4.19.2.0-943b
    containers-0.6.8-bfcf gloss-1.13.2.2-H3MfEzgu5iUIoxuMgX8xst
    mtl-2.3.1-4800 random-1.2.1.3-I6Z7unQx6Hb1B0s3MmJDVF
    time-1.12.2-0f79

haddock-interfaces:
    C:\Users\admin\Desktop\DeclarativaF\MathDoku\.stack-work\install\cfaefed7\doc\MathDoku-1.0.0.0\MathDoku.haddock

haddock-html:
    C:\Users\admin\Desktop\DeclarativaF\MathDoku\.stack-work\install\cfaefed7\doc\MathDoku-1.0.0.0
