name:                 MathDoku
version:              1.0.0.0
visibility:           public
id:                   MathDoku-1.0.0.0-FMXTVG2poHG8uCupkq3zAm
key:                  MathDoku-1.0.0.0-FMXTVG2poHG8uCupkq3zAm
license:              MIT
copyright:            2025
maintainer:           you@team.com
author:               Your team
homepage:             https://github.com/fabio2k3/MathDoku#readme
synopsis:             Interactive mathematical sudoku with hints
category:             Game
abi:                  8987056625360b22832be8a992dd0a16
exposed:              True
exposed-modules:
    MathDoku MathDoku.Core MathDoku.GameState MathDoku.Generator
    MathDoku.Hints MathDoku.Solver MathDoku.UI MathDoku.UIHints

hidden-modules:       Paths_MathDoku
import-dirs:
    C:\Users\admin\Desktop\DeclarativaF\MathDoku\.stack-work\install\8e428229\lib\x86_64-windows-ghc-8.10.7\MathDoku-1.0.0.0-FMXTVG2poHG8uCupkq3zAm

library-dirs:
    C:\Users\admin\Desktop\DeclarativaF\MathDoku\.stack-work\install\8e428229\lib\x86_64-windows-ghc-8.10.7\MathDoku-1.0.0.0-FMXTVG2poHG8uCupkq3zAm
    C:\Users\admin\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\admin\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    C:\Users\admin\Desktop\DeclarativaF\MathDoku\.stack-work\install\8e428229\lib\x86_64-windows-ghc-8.10.7
    C:\Users\admin\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\admin\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    C:\Users\admin\Desktop\DeclarativaF\MathDoku\.stack-work\install\8e428229\share\x86_64-windows-ghc-8.10.7\MathDoku-1.0.0.0

hs-libraries:         HSMathDoku-1.0.0.0-FMXTVG2poHG8uCupkq3zAm
include-dirs:
    C:\Users\admin\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include

depends:
    MonadRandom-0.5.3-1AfKRgFerBj5Oq1Oav4LH base-4.14.3.0
    containers-0.6.5.1 gloss-1.13.2.1-D0DWqwqH5FM7COJ90qifNp mtl-2.2.2
    random-1.2.0-GAV679NMk7iDELNoxF99p4 text-1.2.4.1 time-1.9.3

haddock-interfaces:
    C:\Users\admin\Desktop\DeclarativaF\MathDoku\.stack-work\install\8e428229\doc\MathDoku-1.0.0.0\MathDoku.haddock

haddock-html:
    C:\Users\admin\Desktop\DeclarativaF\MathDoku\.stack-work\install\8e428229\doc\MathDoku-1.0.0.0
